# Generated by Django 2.2.13 on 2021-01-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('to', models.IntegerField()),
                ('linkId', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ('-date',)},
        ),
    ]
