# Generated by Django 2.2.13 on 2021-01-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_auto_20210114_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsinbox',
            options={'ordering': ('-date',), 'verbose_name': 'SmsInbox', 'verbose_name_plural': 'SmsInbox'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ('-date',), 'verbose_name': 'SmsLog', 'verbose_name_plural': 'SmsLog'},
        ),
    ]
