# Generated by Django 2.2.13 on 2021-01-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_auto_20210114_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('retryCount', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('networkCode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Delivery Report',
                'verbose_name_plural': 'Delivery Reports',
                'ordering': ('-date',),
            },
        ),
    ]
