# Generated by Django 2.2.13 on 2021-01-15 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0005_auto_20210115_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
