# Generated by Django 2.2.13 on 2021-01-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_auto_20210115_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmsInbox',
            new_name='Inbox',
        ),
        migrations.RenameModel(
            old_name='SmsLog',
            new_name='Outbox',
        ),
        migrations.AlterModelOptions(
            name='inbox',
            options={'ordering': ('-date',), 'verbose_name': 'Inbox', 'verbose_name_plural': 'Inbox'},
        ),
        migrations.AlterModelOptions(
            name='outbox',
            options={'ordering': ('-date',), 'verbose_name': 'Outbox', 'verbose_name_plural': 'Outbox'},
        ),
    ]
